In [ ]:
# The dataset to use for this assignment is the Iris dataset, which is a 
# classic and very easy to-use multiclass classification dataset. It consists 
# of the petal and sepal lengths of three  different types of irises (setosa, 
# versicolor, and virginica), stored in a 150 × 4 numpy.ndarray. The rows 
# are the samples and the columns are Sepal Length, Sepal Width, Petal  
# Length, and Petal Width.  You can load the Iris dataset through this 
# Python code:  
    
#     from sklearn import datasets  
#     iris = datasets.load_iris()  
    
# We will use SVM here, but with different kernels. In the chapter we only 
# briefly talked  about what a kernel is. Essentially, a kernel is a function 
# that allows the data points to be  mapped in a higher-dimensional space to 
# create a separating boundary between classes.  This transformation could be 
# as simple as linear. Here is how you can build an SVM with  a linear kernel:
 
#     from sklearn.svm import SVC #importing the package  
#     SVC(kernel="linear") #building the classifier  
    
# The second line will give you a classifier that you can store and process 
# further, just like  you do with a kNN-built classifier. Here we are saying 
# that we want to use a linear kernel  for our SVM. Other options are “rbf” 
# (radial basis function) and “poly” (polynomial). Try  each of these and see
# what accuracies you get. Note that every time you run your program  you may
# get slightly different numbers, so try running it a few times:  
#     • For the classification, take only the first two columns from the 
#       dataset.  
#     • Split the dataset into 70% for training and 30% for testing.  
#     • Show the resulting accuracies for the three variations of SVM. 

In [23]:
from sklearn.model_selection import train_test_split
import pandas as pd  
import numpy as np  
from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVR
from sklearn.metrics import accuracy_score, confusion_matrix, mean_squared_error, r2_score

# Import and print dataset for evaluation and preparation of data
df = pd.read_csv("../Datasets/Code_and_Data_(Chapter_06)/Code and Data (Chapter 06)/Iris.csv", index_col="Id")
# print (df)

# Encode string values categorically with a numeric label
df['Species'].replace(['Iris-setosa','Iris-virginica', 'Iris-versicolor'], [0, 1, 2], inplace=True)

X = df.drop(columns=['Species'])
y = df.Species

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [26]:
# Build, train, and evaluate an SVR model
regressor = SVR(kernel='rbf')  
regressor.fit(X_train, y_train) 

y_pred = regressor.predict(X_test)

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Mean Squared Error: {mse}")
print(f"R-squared: {r2}")

# Build, train, and evaluate an SVC model with linear kernel
svm_model = SVC(kernel='linear')
svm_model.fit(X_train, y_train)

svm_predictions = svm_model.predict(X_test) 
svm_accuracy = accuracy_score(y_test, svm_predictions) 
svm_confusion_matrix = confusion_matrix(y_test, svm_predictions) 

print("\n\nSVM (linear) Accuracy:", svm_accuracy)  
print("SVM Confusion Matrix:\n", svm_confusion_matrix)

# Build, train, and evaluate an SVC model with polynomial kernel
svm_model = SVC(kernel='poly')
svm_model.fit(X_train, y_train)

svm_predictions = svm_model.predict(X_test) 
svm_accuracy = accuracy_score(y_test, svm_predictions) 
svm_confusion_matrix = confusion_matrix(y_test, svm_predictions) 

print("\n\nSVM (polynomial) Accuracy:", svm_accuracy)  
print("SVM Confusion Matrix:\n", svm_confusion_matrix)

# Build, train, and evaluate an SVC model with radial base function kernel
svm_model = SVC(kernel='rbf')
svm_model.fit(X_train, y_train)

svm_predictions = svm_model.predict(X_test) 
svm_accuracy = accuracy_score(y_test, svm_predictions) 
svm_confusion_matrix = confusion_matrix(y_test, svm_predictions) 

print("\n\nSVM (radial base function) Accuracy:", svm_accuracy)  
print("SVM Confusion Matrix:\n", svm_confusion_matrix)

Mean Squared Error: 0.04301187053614585
R-squared: 0.9379636482651742


SVM (linear) Accuracy: 1.0
SVM Confusion Matrix:
 [[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]


SVM (polynomial) Accuracy: 0.9777777777777777
SVM Confusion Matrix:
 [[19  0  0]
 [ 0 13  0]
 [ 0  1 12]]


SVM (radial base function) Accuracy: 1.0
SVM Confusion Matrix:
 [[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
